name: 2d-playground
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.7 # Specify the Python version; adjust as needed
  - matplotlib
  - numpy
  - pytorch
  - typer
  - pyyaml
  - moviepy
  - pillow
  - rich
  - scipy
  - pip
  - pip:
    - schedulefree
